### ISSUE TITLE
Missing DLL file

### ISSUE THREAD

**Issue by 1143966219** [ModByDaylight/PrivateServer#20]
When I open the private server, many windows tell me that the DLL file is missing, but I have installed the private server file

**Comment by BrandonItaly** [comment]
This will be fixed in a future release. As a temporary solution, you can download [Visual Studio](https://visualstudio.microsoft.com/thank-you-downloading-visual-studio/?sku=Community&channel=Release&version=VS2022&source=VSLandingPage&cid=2030&passive=false) and install Desktop development with C++.
